---
- hosts: master_node
  remote_user: root

  tasks:
  - name: Disable Swap
    shell: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Disable Swap on future startups
    replace:
     path: /etc/fstab
     regexp: '^(/dev/mapper/ol-swap*)'
     replace: '#\1'

  - name: Disable Firewall
    systemd:
      name: firewalld
      state: stopped
      enabled: no

  - name: Add Utils packages
    yum:
      name:
        - vim
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - bind-utils
      state: present

  - name: Add Docker YUM repository
    get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

  - name: Install Docker Packages
    yum:
     name:
       - http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.107-3.el7.noarch.rpm #TODO: Add CentOS Extra yum repo instead of URL
       - docker-ce
       - docker-ce-cli
       - containerd.io
     state: present

  - name: Start Docker Service
    systemd:
      name: docker
      state: started
      enabled: yes

  - name: Add Google Cloud YUM GPG Key
    rpm_key:
      key: https://packages.cloud.google.com/yum/doc/yum-key.gpg
      state: present

  - name: Add Google Cloud Package GPG Key
    rpm_key:
      key: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      state: present

  - name: Add Kubernetes YUM repository
    yum_repository:
      name: Kubernetes
      description: Kubernetes YUM repository
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64

  - name: Install Kubernetes Packages
    yum:
      name:
        - kubelet 
        - kubeadm 
        - kubectl
      state: present

  - name: Configure node IP
    lineinfile:
      path: /etc/default/kubelet
      line: KUBELET_EXTRA_ARGS=--node-ip={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}
      create: yes
    register: configure_node_ip

  - name: Get Kubelet service status
    shell: "systemctl status kubelet.service"
    register: kubelet_status
    changed_when: "'could not be found' in kubelet_status.stdout"
    failed_when: false

  - name: Init Kubernetes cluster
    shell: kubeadm init --apiserver-advertise-address="{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}" --apiserver-cert-extra-sans="{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}" --node-name {{ inventory_hostname }} --pod-network-cidr={{ (hostvars[inventory_hostname]['ansible_default_ipv4']['network'] + '/' + hostvars[inventory_hostname]['ansible_default_ipv4']['netmask']) | ipaddr('network/prefix') }}
    when:  kubelet_status.changed == true # Idempotence: We supose if kubelet service is present, cluster has been already initialized 
    # TODO: Only on Master Node

  - name: Set KUBECONFIG on .bash_profile
    lineinfile:
      path: /root/.bash_profile
      line: "export KUBECONFIG=/etc/kubernetes/admin.conf"
